-- Stars, calendar times, and the rich-notes subsystem.
--
-- `notes` deliberately allows either task_id or cluster_id (exactly one of them) so a note
-- can hang off a single task or off the cluster as a whole, without two near-identical
-- tables.
--
-- Private notes are the one place where workspace membership is NOT sufficient to read a
-- row: the SELECT/ALL policy requires visibility = 'workspace' OR created_by = auth.uid().
-- That check lives in the policy rather than app code so a shared workspace can never leak
-- someone's private note through any query path, including realtime and the REST API.

alter table public.tasks add column if not exists starred boolean not null default false;

-- Calendar sync only picks up tasks that carry an explicit time, so this is nullable and
-- separate from the existing date-only `deadline` column.
alter table public.tasks add column if not exists deadline_time text;

-- Drives the 4-month idle sweep into cold storage.
alter table public.clusters add column if not exists last_used_at timestamptz not null default now();

create index if not exists tasks_starred_idx on public.tasks (workspace_id, starred);
create index if not exists clusters_last_used_idx on public.clusters (workspace_id, last_used_at);

create table if not exists public.notes (
  id bigint generated by default as identity primary key,
  workspace_id bigint not null references public.workspaces(id) on delete cascade,
  task_id bigint references public.tasks(id) on delete cascade,
  cluster_id bigint references public.clusters(id) on delete cascade,
  created_by uuid not null references public.users(id) on delete cascade,
  kind text not null default 'text',
  visibility text not null default 'workspace',
  body text not null default '',
  url text,
  mime text,
  size_bytes bigint not null default 0,
  duration_ms integer,
  pos integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint notes_kind_check check (kind in ('text', 'rich', 'code', 'link', 'image', 'video', 'voice', 'table')),
  constraint notes_visibility_check check (visibility in ('workspace', 'private')),
  constraint notes_one_parent check (num_nonnulls(task_id, cluster_id) = 1)
);

create index if not exists notes_task_idx on public.notes (task_id);
create index if not exists notes_cluster_idx on public.notes (cluster_id);
create index if not exists notes_workspace_idx on public.notes (workspace_id);
create index if not exists notes_author_idx on public.notes (created_by);

alter table public.notes enable row level security;

drop policy if exists "workspace members read visible notes" on public.notes;
create policy "workspace members read visible notes" on public.notes
  for select using (
    public.is_workspace_member(workspace_id, auth.uid())
    and (visibility = 'workspace' or created_by = auth.uid())
  );

drop policy if exists "workspace members insert own notes" on public.notes;
create policy "workspace members insert own notes" on public.notes
  for insert with check (
    public.is_workspace_member(workspace_id, auth.uid())
    and created_by = auth.uid()
  );

-- Only the author can change or remove a note, private or not — a workspace-mate editing
-- someone else's note isn't a flow the app has.
drop policy if exists "authors update own notes" on public.notes;
create policy "authors update own notes" on public.notes
  for update using (
    public.is_workspace_member(workspace_id, auth.uid()) and created_by = auth.uid()
  ) with check (
    public.is_workspace_member(workspace_id, auth.uid()) and created_by = auth.uid()
  );

drop policy if exists "authors delete own notes" on public.notes;
create policy "authors delete own notes" on public.notes
  for delete using (
    public.is_workspace_member(workspace_id, auth.uid()) and created_by = auth.uid()
  );

-- ---- media storage (voice notes, photos, video) ----
insert into storage.buckets (id, name, public, file_size_limit)
values ('note-media', 'note-media', false, 104857600)
on conflict (id) do nothing;

-- Objects are keyed as `<auth.uid()>/<filename>`, so the first path segment is the owner
-- and doubles as the per-user quota namespace.
drop policy if exists "note media readable by owner" on storage.objects;
create policy "note media readable by owner" on storage.objects
  for select using (bucket_id = 'note-media' and (storage.foldername(name))[1] = auth.uid()::text);

drop policy if exists "note media writable by owner" on storage.objects;
create policy "note media writable by owner" on storage.objects
  for insert with check (bucket_id = 'note-media' and (storage.foldername(name))[1] = auth.uid()::text);

drop policy if exists "note media deletable by owner" on storage.objects;
create policy "note media deletable by owner" on storage.objects
  for delete using (bucket_id = 'note-media' and (storage.foldername(name))[1] = auth.uid()::text);

-- Bytes a user has stored across every workspace, for the 10 GB per-user quota. Runs as
-- definer so it can total rows the caller can't select (their own notes in workspaces the
-- request isn't scoped to).
create or replace function public.user_storage_used(p_user_id uuid)
returns bigint
language sql
security definer
stable
set search_path = public
as $$
  select coalesce(sum(size_bytes), 0)::bigint from public.notes where created_by = p_user_id;
$$;

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'notes'
  ) then
    alter publication supabase_realtime add table public.notes;
  end if;
end $$;
